project: grafx_prune # project name that will be used in wandb
base_dir: /workspace/grafx_prune

id: null
debug: false
wandb: true
inference: false
pickle_path: null

sr: 30000
audio_len: 114000
batch_size: 1
steps_per_epoch: 500
total_epochs: 24

multiple_runs: false
num_splits: 10
split_id: 0
datasets: 
  - medley
  - mixing_secrets
dataset_split: valid

dataset: null
song: null

processors: 
  - eq
  - compressor
  - noisegate
  - stereo_imager
  - gain_panning
  - delay
  - reverb

flashfftconv: true

lr: 1.e-2
gain_reg_weight: 1.e-3

prune: false
prune_policy: hybrid
tolerance: 1.e-2
prune_start_epoch: 12
sparsity_loss_weight: 1.e-4
sparsity_raise_epoch: 4

num_steps_per_log: 50
save_intermediate_graphs: false

consistency_check: false
consistency_check_target: null
